x = room_width / 2
y = room_height / 2
lives = 5
global.shot_defined = false
file = file_text_open_write(global.repeats)
can_shoot = true;
is_down = true;
is_right = false;
is_dead = false
dead_cnt = 0